#!/usr/bin/env bash
# bootstrap-gitbash.sh — set up Astropress for local dev from Git Bash (Git for Windows).
#
# WHY THIS EXISTS
#   The repo's tooling/scripts/install.sh targets macOS/Linux/BSD and *dies* on
#   Windows because `uname -s` returns MINGW64_NT-* / MSYS_NT-*, and it relies on
#   nvm + sudo apt/dnf + the rustup shell script, none of which work cleanly in
#   Git Bash. tooling/scripts/install.ps1 is the supported Windows installer, but
#   it is PowerShell. This script lets you bootstrap the *repo* from Git Bash:
#   it does NOT install system toolchains (use winget for those — it prints the
#   exact commands), then runs the repo-level steps that DO work in Git Bash
#   (bun install, Playwright browsers, cargo build, .env, a light check).
#
# USAGE (from the repo root, in Git Bash):
#   bash scripts/bootstrap-gitbash.sh                # full
#   bash scripts/bootstrap-gitbash.sh --skip-playwright
#   bash scripts/bootstrap-gitbash.sh --skip-build   # skip cargo build
# Safe to re-run.
set -uo pipefail

CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BOLD='\033[1m'; RESET='\033[0m'
info(){ echo -e "${CYAN}[info]${RESET}  $*"; }
ok(){   echo -e "${GREEN}[ok]${RESET}    $*"; }
warn(){ echo -e "${YELLOW}[warn]${RESET}  $*"; }
die(){  echo -e "${RED}[error]${RESET} $*" >&2; exit 1; }
section(){ echo -e "\n${BOLD}== $* ==${RESET}"; }
has(){ command -v "$1" >/dev/null 2>&1; }

SKIP_PLAYWRIGHT=false; SKIP_BUILD=false
for a in "$@"; do case "$a" in
  --skip-playwright) SKIP_PLAYWRIGHT=true ;;
  --skip-build)      SKIP_BUILD=true ;;
esac; done

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"; cd "$ROOT" || die "cd failed"
section "Astropress Git Bash bootstrap"
info "Repo root: $ROOT"

case "$(uname -s)" in
  MINGW*|MSYS*) ok "Git Bash / MSYS detected." ;;
  *) warn "This is not Git Bash. On macOS/Linux just run tooling/scripts/install.sh instead." ;;
esac

# ── 1. Prerequisite check (does NOT auto-install system tools) ────────────────
section "Prerequisites"
MISSING=0
need_winget_hint=""

check_git(){ if has git; then ok "git $(git --version | awk '{print $3}')"; else MISSING=1; need_winget_hint+=$'\n  winget install --id Git.Git -e'; warn "git missing"; fi; }
check_node(){
  if has node; then
    local maj; maj="$(node -e 'process.stdout.write(String(process.versions.node.split(".")[0]))' 2>/dev/null || echo 0)"
    if [ "${maj:-0}" -ge 24 ]; then ok "node $(node --version)"; else warn "node $(node --version) too old (need >= 24.8)"; MISSING=1; need_winget_hint+=$'\n  winget install --id OpenJS.NodeJS -e   # then reopen Git Bash'; fi
  else MISSING=1; need_winget_hint+=$'\n  winget install --id OpenJS.NodeJS -e'; warn "node missing (need >= 24.8)"; fi
}
check_bun(){
  if has bun; then
    local m; m="$(bun --version | cut -d. -f1-2)"
    if [ "$m" = "1.3" ]; then ok "bun $(bun --version)"; else warn "bun $(bun --version) — repo pins 1.3.x"; fi
  else MISSING=1; need_winget_hint+=$'\n  winget install --id Oven-sh.Bun -e   # or: powershell -c "irm bun.sh/install.ps1|iex"'; warn "bun missing (need 1.3.x)"; fi
}
check_cargo(){ if has cargo; then ok "cargo $(cargo --version | awk '{print $2}')"; else MISSING=1; need_winget_hint+=$'\n  winget install --id Rustlang.Rustup -e   # then: rustup default stable'; warn "cargo/Rust missing"; fi; }

check_git; check_node; check_bun; check_cargo

if [ "$MISSING" = "1" ]; then
  warn "Some toolchains are missing or too old. Install them on the Windows side"
  warn "(winget is simplest — run these in PowerShell or CMD, then reopen Git Bash):"
  echo -e "${need_winget_hint}"
  warn "Alternatively run the supported installer once:  pwsh tooling/scripts/install.ps1"
  die  "Re-run this script after the toolchains are on PATH."
fi

# ── 2. Dependencies ───────────────────────────────────────────────────────────
section "bun install"
bun install || die "bun install failed"
ok "dependencies installed"

# ── 3. Playwright browsers (admin UI + a11y E2E) ──────────────────────────────
section "Playwright browsers"
if [ "$SKIP_PLAYWRIGHT" = true ]; then
  warn "skipped (--skip-playwright)"
else
  info "Installing Chromium, Firefox, WebKit (browser binaries)…"
  bun x playwright install chromium firefox webkit || \
    warn "Playwright install hit an issue; UI E2E may not run locally. You can retry later."
fi

# ── 4. .env (local dev defaults) ──────────────────────────────────────────────
section ".env"
if [ -f .env ]; then
  ok ".env already exists — leaving it"
else
  info "Creating .env with local dev defaults…"
  if has openssl; then SECRET="$(openssl rand -hex 32)"; else SECRET="$(tr -dc 'a-f0-9' </dev/urandom | head -c 64)"; fi
  cat > .env <<ENVEOF
# Astropress local development environment (generated by bootstrap-gitbash.sh)
ASTROPRESS_RUNTIME_MODE=local
ASTROPRESS_LOCAL_PROVIDER=sqlite
SESSION_SECRET=${SECRET}
ADMIN_PASSWORD=admin123
EDITOR_PASSWORD=editor123
EMAIL_DELIVERY_MODE=mock
NEWSLETTER_DELIVERY_MODE=mock
ENVEOF
  ok ".env created (random SESSION_SECRET)"
  warn "ADMIN_PASSWORD is 'admin123' — change it before any shared/hosted deployment."
fi

# ── 5. Build the Rust CLI ─────────────────────────────────────────────────────
section "Rust CLI"
if [ "$SKIP_BUILD" = true ]; then
  warn "skipped (--skip-build)"
else
  info "cargo build --manifest-path crates/Cargo.toml --bin astropress-cli (debug)…"
  cargo build --manifest-path crates/Cargo.toml --bin astropress-cli || warn "cargo build failed — fix toolchain, then re-run."
  [ -x crates/target/debug/astropress-cli ] && ok "CLI built: crates/target/debug/astropress-cli" || \
    [ -x crates/target/debug/astropress-cli.exe ] && ok "CLI built: crates/target/debug/astropress-cli.exe"
fi

# ── 6. Light check ────────────────────────────────────────────────────────────
section "Quick check"
bun run audit:arch >/dev/null 2>&1 && ok "audit:arch passed" || warn "audit:arch reported issues (expected only if you've edited code)"

section "Done"
cat <<SUMMARY

${GREEN}${BOLD}Astropress is bootstrapped for Git Bash.${RESET}

Next:
  1. Scaffold a site (from the repo root):
       cargo run --manifest-path crates/Cargo.toml --bin astropress-cli -- new my-site --provider sqlite
       cd my-site && bun install
       ../crates/target/debug/astropress-cli dev --project-dir .
     Admin UI:  http://localhost:4321/ap-admin   (admin / admin123)

  2. Place the Claude Code config (if you haven't):
       bash scripts/install-claude-bundle.sh     # copies .claude/ and .vscode/ in

  3. Open in VS Code and accept the recommended extensions (incl. Claude Code).

  Note: if launching the Claude Code REPL inside the classic Git Bash (MinTTY)
  window throws "Raw mode is not supported", start it from Windows Terminal or
  PowerShell instead — Claude Code still uses Git Bash under the hood.
SUMMARY
